services:
  chuck_norris_service:
    build:
      context: .
      ssh:
        - default
    container_name: chuck_norris_container
    depends_on:
      - redis
    networks:
      - default
      - shared_network

  redis:
    image: redis:6.2
    container_name: chuck_norris_redis
    ports:
      - "6387:6379"
    networks:
      - default

networks:
  shared_network:
    external: true
