version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: shared_rabbitmq
    ports:
      - "5698:5672"
      - "15698:15672"
    environment:
      RABBITMQ_DEFAULT_USER: punchline_user
      RABBITMQ_DEFAULT_PASS: punchline_password
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network