services:
  postgres-dev:
    container_name: punchline_postgres_dev
    image: postgres:16.3
    environment:
      POSTGRES_USER: punchline_user
      POSTGRES_PASSWORD: punchline_password
      POSTGRES_DB: punchline_db
    ports:
      - "5477:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - punchline_api_network_dev


volumes:
  postgres_data_dev:

networks:
  punchline_api_network_dev: